CREATE TABLE Product_codes (id SERIAL PRIMARY KEY, prod_code_abbrev TEXT UNIQUE NOT NULL, prod_code_name TEXT NOT NULL);
CREATE TABLE Products (id SERIAL PRIMARY KEY, donation_number TEXT UNIQUE NOT NULL, product_code_id INTEGER REFERENCES Product_codes ON DELETE RESTRICT, bloodgroup TEXT NOT NULL, phenotypes TEXT, use_before DATE NOT NULL);
CREATE TABLE Patients (id SERIAL PRIMARY KEY, ssn TEXT UNIQUE NOT NULL, patient_name TEXT NOT NULL, bloodgroup TEXT NOT NULL, phenotype_reqs TEXT);
CREATE TABLE Inventories (id SERIAL PRIMARY KEY, inventory_abbrev TEXT UNIQUE NOT NULL, inventory_name TEXT NOT NULL);
CREATE TABLE Departments (id SERIAL PRIMARY KEY, department_abbrev TEXT UNIQUE NOT NULL, department_name TEXT NOT NULL, inventory_id INTEGER REFERENCES Inventories ON DELETE RESTRICT);
CREATE TABLE Inventory_products (id SERIAL PRIMARY KEY, product_id INTEGER REFERENCES Products ON DELETE CASCADE, inventory_id INTEGER REFERENCES Inventories ON DELETE RESTRICT, status TEXT NOT NULL);
CREATE TABLE Transfusions (id SERIAL PRIMARY KEY, product_id INTEGER REFERENCES Products ON DELETE RESTRICT, patient_id INTEGER REFERENCES Patients ON DELETE RESTRICT, department_id INTEGER REFERENCES Departments ON DELETE RESTRICT, date DATE NOT NULL);
CREATE TABLE Users (id SERIAL PRIMARY KEY, username TEXT UNIQUE NOT NULL, password TEXT NOT NULL, salt TEXT NOT NULL, role INTEGER NOT NULL);
CREATE TABLE Logs (id SERIAL PRIMARY KEY, logtext TEXT NOT NULL, user_id INTEGER REFERENCES Users ON DELETE RESTRICT, date DATE NOT NULL);